"""add_game_columns_to_apero

Revision ID: 883ae2b8ae13
Revises: 1ea8c26a76d9
Create Date: 2026-05-11 18:00:03.758789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883ae2b8ae13'
down_revision: Union[str, Sequence[str], None] = '1ea8c26a76d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aperos', sa.Column('current_game_id', sa.String(), nullable=True))
    op.add_column('aperos', sa.Column('current_game_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aperos', 'current_game_state')
    op.drop_column('aperos', 'current_game_id')
    # ### end Alembic commands ###
