"""add_websocket_tickets

Revision ID: d42a6f8b1c30
Revises: 9c4e6f2a1b7d
Create Date: 2026-10-09 20:22:00.909081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42a6f8b1c30'
down_revision: Union[str, Sequence[str], None] = '9c4e6f2a1b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_tickets_digest'), 'websocket_tickets', ['digest'], unique=True)
    op.create_index('ix_websocket_tickets_squad_expires', 'websocket_tickets', ['squad_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_websocket_tickets_squad_expires', table_name='websocket_tickets')
    op.drop_index(op.f('ix_websocket_tickets_digest'), table_name='websocket_tickets')
    op.drop_table('websocket_tickets')
    # ### end Alembic commands ###
