"""add_beer_call_jobs

Revision ID: e53b7a9c2d41
Revises: d42a6f8b1c30
Create Date: 2026-10-09 20:38:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53b7a9c2d41'
down_revision: Union[str, Sequence[str], None] = 'd42a6f8b1c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_call_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'PENDING', 'RUNNING', 'SUCCEEDED', 'REJECTED', 'FAILED', name='beercalljobstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'idempotency_key', name='uix_beer_call_job_creator_idempotency')
    )
    op.create_table('realtime_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_realtime_events_dispatched_at', 'realtime_events', ['dispatched_at'], unique=False)
    with op.batch_alter_table('aperos') as batch_op:
        batch_op.add_column(sa.Column('source_job_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_aperos_source_job_id', 'beer_call_jobs', ['source_job_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint('uq_aperos_source_job_id', ['source_job_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aperos') as batch_op:
        batch_op.drop_constraint('uq_aperos_source_job_id', type_='unique')
        batch_op.drop_constraint('fk_aperos_source_job_id', type_='foreignkey')
        batch_op.drop_column('source_job_id')
    op.drop_index('ix_realtime_events_dispatched_at', table_name='realtime_events')
    op.drop_table('realtime_events')
    op.drop_table('beer_call_jobs')
    sa.Enum('UPLOADING', 'PENDING', 'RUNNING', 'SUCCEEDED', 'REJECTED', 'FAILED', name='beercalljobstatus').drop(op.get_bind())
    # ### end Alembic commands ###